### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by hyder365** [r-a-y/mobile-hosts#17]
https://raw.githubusercontent.com/r-a-y/mobile-hosts/master/EasyPrivacySpecific.txt

This list is blocking soundcloud.com, which is obviously not malicious.

**Comment by r-a-y** [comment]
Thanks for the report.

My converter strips out special ad filter syntaxes like `$ping` in order to block those domains. Unfortunately, the EasyPrivacy Specific list uses `$ping` for the `soundcloud.com` domain :
https://github.com/easylist/easylist/blob/320e65cf82b21efed242bdd387bca769b403631d/easyprivacy/easyprivacy_specific.txt#L602

I guess I can write an exception to skip SoundCloud.

**Comment by r-a-y** [comment]
Latest EasyPrivacySpecific update removes Soundcloud: https://github.com/r-a-y/mobile-hosts/commit/8c56b939bed6ca25115cb4d555b456c76e2ae4bf

Thanks again for the report!
