### ISSUE TITLE
What should China add

### ISSUE THREAD

**Issue by biange200** [r-a-y/mobile-hosts#20]
Hello, what rules do you apply to China
The persondns filter is installed on my mobile phone
I find your rules don't work in blokada No effect

**Comment by r-a-y** [comment]
If you're using the Adguard DNS filter, you need to enable CNAME blocking in your filtering app. It looks like Blokada v4 has an option to do this: https://community.blokada.org/t/cname-blocking-with-blokada/3573

However, I would recommend using personalDNSfilter instead of Blokada. You can get it from F-Droid: https://f-droid.org/en/packages/dnsfilter.android/. Then in personalDNSfilter, you can enable the "CNAME cloaking protection" option. For instructions, see https://www.zenz-solutions.de/help/.

If you're using Chrome, you have to disable async DNS: https://www.xda-developers.com/fix-dns-ad-blocker-chrome/.

If you don't want to use an app and you're using Android 9 or above, you can use Android's built-in private DNS feature instead. See https://www.androidsage.com/2018/12/25/how-to-block-ads-using-private-dns-dns-over-tls-feature/.

**Comment by biange200** [comment]
I use pdnsf now
personalDNSfilter

**Comment by r-a-y** [comment]
Going to close this ticket. If you have any other questions, let me know.
