### ISSUE TITLE
trib.al

### ISSUE THREAD

**Issue by p1r473** [r-a-y/mobile-hosts#22]
This is Twitter's URL Shortener domain
This is not inherently malicious

**Comment by r-a-y** [comment]
Thanks for the report.

It's due to the following ad filter in EasyPrivacy's 3rd-Party list: https://github.com/easylist/easylist/blob/606bbb7055c4a21e9dde0e934ea0c602b37720f8/easyprivacy/easyprivacy_thirdparty.txt#L1955

My converter strips out the `$image,third-party` portion, so this would result in the entire `trib.al` domain being blocked.

If you use AdAway or a similar tool, you can write your own exception to allow `trib.al`. I did some brief research and found that it is a URL shortener and analytics tool, not necessarily connected to Twitter, so I'm comfortable leaving it blocked. Also see: https://www.hanselman.com/blog/this-url-shortener-situation-is-officially-out-of-control.

If you need to expand tri.bal URLs, you could use a site like `https://www.expandurl.net/`.

**Comment by p1r473** [comment]
I have it whitelisted locally- just reporting it in case other people are getting their links blocked
