### ISSUE TITLE
false positive

### ISSUE THREAD

**Issue by namtsui** [r-a-y/mobile-hosts#26]
https://github.com/r-a-y/mobile-hosts/blob/b3300d46283a12c76c6eb67568449a8fd7aba4ec/EasyPrivacySpecific.txt#L227

global.ssl.fastly.net is a false positive. it breaks https://shop.gandi.net/en/domain/suggest?search=google.com

easylist has the following:

https://github.com/easylist/easylist/blob/5f3401eff0c52e1db27519b80cb346eb90d6aa32/easyprivacy/easyprivacy_specific.txt#L479

**Comment by r-a-y** [comment]
Thanks for listing where EasyList is declaring their rule. My converter strips the `$domain` rule, so that would cover all domains: https://github.com/r-a-y/mobile-hosts/blob/b3300d46283a12c76c6eb67568449a8fd7aba4ec/converter.php#L75-L78

I might remove the `$domain` stripping if I get more false positive reports, but for now I'll write an exception for `global.ssl.fastly.net`. Thanks @namtsui !

**Comment by r-a-y** [comment]
EasyPrivacySpecific.txt has been updated to exclude `global.ssl.fastly.net`: https://github.com/r-a-y/mobile-hosts/commit/a87bb24468d549c279e00a81bfeaa2a1e70532ae

Thanks!
