### ISSUE TITLE
Questions about AdGuard DNS

### ISSUE THREAD

**Issue by superlex** [r-a-y/mobile-hosts#4]
Hi,
first of all, thanks for your work :)
Then, I've two questions for you:
- why do you use chromium list instead of the regular one?
https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
- what about adguar dns whitelisted domains (e.g. sas[dot]com)? Should your script remove them?

**Comment by r-a-y** [comment]
Thanks for the questions :)

About the first question, you are right that there appears to be a few, minor differences between the two lists.  I'll switch to your link for the next update.

About the second question, that's a little harder because if you do a search for `sas.com` in the list, it's added as a filter first and later added as an exception filter down the list.  For me to remove these exception filters, I'd need to parse the entire list and remove theme.  I'll look into this.

In the meantime, I'll leave this issue open until I've had time to look into it.

**Comment by superlex** [comment]
> About the first question, you are right that there appears to be a few, minor differences between the two lists. I'll switch to your link for the next update.


Ok :)

> About the second question, that's a little harder because if you do a search for sas.com in the list, it's added as a filter first and later added as an exception filter down the list. For me to remove these exception filters, I'd need to parse the entire list and remove them. I'll look into this.

Yep, in most cases only subdomains are whitelisted and there is no need to do it (being an hosts file), but in the future there may be other cases like sas (and they should be deleted from final hosts file by parsing the entire list as you said).

> In the meantime, I'll leave this issue open until I've had time to look into it.

Ok :)

However, I saw there are some adresses (like`37.220.26.135`): should they be removed because useless? 

Thanks again.

**Comment by r-a-y** [comment]
Latest update has added the ability to parse exception filter rules and removes these exceptions from the generated HOSTS file.  Also AdguardDNS link uses the Github one now.

> However, I saw there are some adresses (like37.220.26.135): should they be removed because useless?

These entries are not useless. If you manually type in that IP address, it would resolve.  If malicious scripts or apps are using these IP addresses and you are using the AdguardDNS blocklist, these requests will be blocked.

Going to close this one out.  Thanks for your suggestions, @superlex!

**Comment by superlex** [comment]
Ah, ok :)
Thanks to you :)
